name: Internal Nmap network scan

on:
  workflow_dispatch:

jobs:
  scan:
    permissions:
      contents: read
      id-token: write

    uses: arnold-sa/gcp-security-workflows/.github/workflows/nmap-internal-scan.yml@dev
    with:
      target_cidr: ${{ vars.SCAN_TARGET_CIDR }}
      results_bucket: project_trivy_1
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      RESULTS_UPLOADER_SA: ${{ secrets.RESULTS_UPLOADER_SA }}